{{ if .Values.scheduler.enable }}
  {{ if .Values.scheduler.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "mageai.fullname" . }}-hpa-scheduler
  labels:
  {{- include "mageai.scheduler.selectorLabels" . | nindent 6 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "mageai.fullname" . }}-scheduler
  minReplicas: {{ .Values.scheduler.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.scheduler.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.scheduler.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.scheduler.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.scheduler.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.scheduler.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{ end }}
{{ end}}
