apiVersion: v1
kind: Service
metadata:
  name: {{ include "mageai.fullname" . }}
  labels:
    {{- include "mageai.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mageai.web.selectorLabels" . | nindent 4 }}
