{{- if .Values.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.role.namebind }}
subjects:
- kind: ServiceAccount
  name: {{ include "mageai.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ .Values.role.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
